### ISSUE TITLE
CLIENT_ID not getting picked up from <profiledir>/nbconfig/common.json?

### ISSUE THREAD

**Issue by virtualirfan** [jupyter/jupyter-drive#85] opened 2015-03-03 04:28 UTC
The advanced config section of the README.md says that the file nbconfig/common.json will get picked up ... it's not getting picked up. Could be user error.

For now, I'm manually overriding in the code which isn't ideal.
```bash
$ pwd
/home/virtualirfan/.ipython
$ ls -l
total 16
drwxr-xr-x 2 virtualirfan virtualirfan 4096 Mar  1 23:50 extensions
drwxr-xr-x 2 virtualirfan virtualirfan 4096 Mar  1 23:50 nbextensions
drwxr-xr-x 9 virtualirfan virtualirfan 4096 Mar  3 03:49 profile_default
-rw-r--r-- 1 virtualirfan virtualirfan  195 Mar  1 23:50 README
$ cd profile_default/
$ ls
db  history.sqlite  ipython_notebook_config.json  log  nbconfig  pid  security  startup  static
$ cat ipython_notebook_config.json
```
```json
{
  "MixedContentsManager": {
    "filesystem_scheme": [
      {
        "contents": "IPython.html.services.contents.filemanager.FileContentsManager",
        "root": "local"
      },
      {
        "contents": "jupyterdrive.clientsidenbmanager.ClientSideContentsManager",
        "root": "gdrive"
      }
    ]
  },
  "NotebookApp": {
    "tornado_settings": {
      "contents_js_source": "nbextensions/gdrive/mixed-contents"
    },
    "contents_manager_class": "jupyterdrive.mixednbmanager.MixedContentsManager"
  },
  "nbformat": 1
}
```
```bash
$ cat nbconfig/common.json
```
```json
{
"gdrive":
    {
    "METADATA_SCOPE": true,
    "FILE_SCOPE": true,
    "CLIENT_ID": "<ELIDED>"
    },
"mixed_contents":
    {
    "schema": [
      {
        "stripjs": false,
        "contents": "services/contents",
        "root": "local"
      },
      {
        "stripjs": true,
        "contents": "./drive-contents",
        "root": "gdrive"
      }
    ]
  }
}
```

**Comment by KesterTong** [comment] 2015-03-03 05:01
What version of IPython are you using?  This configuration requires some pretty recent changes, which are now part of IPython 3.0 (right @Carreau?) but might not have been part of earlier releases of 3.0.

**Comment by virtualirfan** [comment] 2015-03-03 05:18
iPython 3

**Comment by Carreau** [comment] 2015-03-05 20:34
Sorry, this fell under my radar, and went marked as read. 
Will take a look try to reproduce.

**Comment by Carreau** [comment] 2015-03-05 20:43
Ok, so I doubt jupyterhub will even work with a version of IPtython too old. 

As you seem to mess with the code, can you try to change gapi_utils.js around line 176 to add `console.log ` ?
```
     var authorize = function(opt_withPopup, conf) {
        var config = $.extend({}, default_config, (conf.data||{})['gdrive']);
        console.log(config, conf);
       ... 
```
to see what config is actually received ? 

Everything you do seem correct, and if I do the same, I actually get it to work (well actually not work if I put a random CLIENT_ID, but it does get propagated)

**Comment by KesterTong** [comment] 2015-03-11 18:09
I'm also unable to reproduce this bug.  Suspect that the IPython version is too old.

**Comment by KesterTong** [comment] 2015-03-11 18:19
Actually this is a bug, will be fixed by #89.  The problem was the config was getting passed successfully to the client, so it was hard to notice that the client code could still fail to use this config properly.

**Comment by KesterTong** [comment] 2015-03-11 18:31
Fixed in #89.  Thanks @virtualirfan for finding this bug.

**Comment by virtualirfan** [comment] 2015-03-12 02:16
Most welcome.

**Closed** 2015-03-16 21:22 UTC
Labels: bug

**Comment by malina-kirn** [comment] 2015-09-22 22:59
It's possible this bug has resurfaced in IPython4/Jupyter. I've attempted placing editing the config in the following file locations:
/etc/jupyter/nbconfig/common.json
~/.jupyter/nbconfig/common.json
/etc/jupyter/jupyter_notebook_config.json
For kicks, though I didn't much expect it to work, I also tried:
~/.ipython/profile_default/nbconfig/common.json

None have worked. I've worked around by manually editing gapiutils.js to hard-code my own client_id.

Of course could be user error.
